Repository ISIS3510-MOBILE-T34/SpendiQ_iOS, pull requests merged in 2024-10, with the labels that each got.

#3 Feature/authentication
  SpendiQ/SpendiQ/Authentication/AuthenticationService.swift
  SpendiQ/SpendiQ/Authentication/AuthenticationView.swift
  SpendiQ/SpendiQ/Authentication/AuthenticationViewModel.swift
  SpendiQ/SpendiQ/Authentication/LoginView.swift
  SpendiQ/SpendiQ/Authentication/SignUpView.swift
Labels: enhancement

#4 documentation/ProjectStructureREADME
  README.md
Labels: documentation

#5 Feature/Sensor_FaceID
  SpendiQ/SpendiQ.xcodeproj/project.pbxproj
  SpendiQ/SpendiQ.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SpendiQ/SpendiQ/Authentication/AuthenticationService.swift
  SpendiQ/SpendiQ/Authentication/AuthenticationViewModel.swift
  SpendiQ/SpendiQ/Authentication/ForgotPasswordView.swift
  SpendiQ/SpendiQ/Authentication/HelpView.swift
  SpendiQ/SpendiQ/Authentication/LoginView.swift
  SpendiQ/SpendiQ/Authentication/PrivacyView.swift
  SpendiQ/SpendiQ/Authentication/SignUpView.swift
  SpendiQ/SpendiQ/Authentication/TermsAndConditionsView.swift
Labels: enhancement

#6 UI/home page
  .DS_Store
  SpendiQ/.DS_Store
  SpendiQ/SpendiQ.xcodeproj/project.pbxproj
  SpendiQ/SpendiQ.xcodeproj/project.xcworkspace/xcuserdata/jdsm.xcuserdatad/UserInterfaceState.xcuserstate
  SpendiQ/SpendiQ.xcodeproj/xcuserdata/jdsm.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  SpendiQ/SpendiQ/.DS_Store
  SpendiQ/SpendiQ/Assets.xcassets/PrimarySpendiq.colorset/Contents.json
  SpendiQ/SpendiQ/Assets.xcassets/TabBarColor.colorset/Contents.json
  SpendiQ/SpendiQ/ContentView.swift
  SpendiQ/SpendiQ/Model/BankAccount.swift
  SpendiQ/SpendiQ/Model/Movement.swift
  SpendiQ/SpendiQ/NotificationManager.swift
  SpendiQ/SpendiQ/View/.DS_Store
  SpendiQ/SpendiQ/View/AccountDetail.swift
  SpendiQ/SpendiQ/View/AccountsPage.swift
  SpendiQ/SpendiQ/View/Components/.DS_Store
  SpendiQ/SpendiQ/View/Components/AccountForm.swift
  SpendiQ/SpendiQ/View/Components/DayResume.swift
  SpendiQ/SpendiQ/View/Components/DayResumeTitle.swift
  SpendiQ/SpendiQ/View/Components/GraphBox.swift
  SpendiQ/SpendiQ/View/Components/MovementForm.swift
  SpendiQ/SpendiQ/View/Components/MovementResume.swift
  SpendiQ/SpendiQ/View/Components/TabBar.swift
  SpendiQ/SpendiQ/View/ContentView.swift
  SpendiQ/SpendiQ/View/HomePage.swift
  SpendiQ/SpendiQ/View/ProfilePage.swift
  SpendiQ/SpendiQ/View/PromosPage.swift
  SpendiQ/SpendiQ/ViewModel/BankAccountViewModel.swift
  SpendiQ/SpendiQ/ViewModel/TransactionViewModel.swift
Labels: enhancement

#8 Fixed
  SpendiQ/SpendiQ.xcodeproj/project.xcworkspace/xcuserdata/jdsm.xcuserdatad/UserInterfaceState.xcuserstate
  SpendiQ/SpendiQ/Authentication/AuthenticationService.swift
Labels: bug

#11 fixed files error
  SpendiQ/SpendiQ.xcodeproj/project.pbxproj
  SpendiQ/SpendiQ.xcodeproj/project.xcworkspace/xcuserdata/jdsm.xcuserdatad/UserInterfaceState.xcuserstate
  SpendiQ/SpendiQ/Model/ShopSalesModel.swift
  SpendiQ/SpendiQ/Services/DataService.swift
  SpendiQ/SpendiQ/Services/LocationManager.swift
  SpendiQ/SpendiQ/View/OfferBubbleView.swift
  SpendiQ/SpendiQ/View/OfferDetailView.swift
  SpendiQ/SpendiQ/View/SpecialOffersAlertView.swift
  SpendiQ/SpendiQ/View/SpecialOffersListView.swift
  SpendiQ/SpendiQ/ViewModel/OfferDetailViewModel.swift
  SpendiQ/SpendiQ/ViewModel/SpecialOffersViewModel.swift
Labels: bug

#12 Organization/MVVM
  SpendiQ/SpendiQ.xcodeproj/project.xcworkspace/xcuserdata/cla.xcuserdatad/UserInterfaceState.xcuserstate
  SpendiQ/SpendiQ.xcodeproj/xcuserdata/cla.xcuserdatad/xcschemes/xcschememanagement.plist
  SpendiQ/SpendiQ/Services/AuthenticationService.swift
  SpendiQ/SpendiQ/View/AuthenticationView.swift
  SpendiQ/SpendiQ/View/ForgotPasswordView.swift
  SpendiQ/SpendiQ/View/HelpView.swift
  SpendiQ/SpendiQ/View/LoginView.swift
  SpendiQ/SpendiQ/View/PrivacyView.swift
  SpendiQ/SpendiQ/View/SignUpView.swift
  SpendiQ/SpendiQ/View/TermsAndConditionsView.swift
  SpendiQ/SpendiQ/ViewModel/AuthenticationViewModel.swift
  SpendiQ/build/XCBuildData/588c74212f6ddeed2505b5e3bc8f1115.xcbuilddata/build-request.json
  SpendiQ/build/XCBuildData/588c74212f6ddeed2505b5e3bc8f1115.xcbuilddata/description.msgpack
  SpendiQ/build/XCBuildData/588c74212f6ddeed2505b5e3bc8f1115.xcbuilddata/manifest.json
  SpendiQ/build/XCBuildData/588c74212f6ddeed2505b5e3bc8f1115.xcbuilddata/target-graph.txt
  SpendiQ/build/XCBuildData/588c74212f6ddeed2505b5e3bc8f1115.xcbuilddata/task-store.msgpack
Labels: Structure

#13 Bugfix/offer list errors and Clarification for Julián Mora Commits
  .DS_Store
  README.md
  SpendiQ/.DS_Store
  SpendiQ/SpendiQ.xcodeproj/project.pbxproj
  SpendiQ/SpendiQ.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SpendiQ/SpendiQ.xcodeproj/project.xcworkspace/xcuserdata/j.morav.xcuserdatad/UserInterfaceState.xcuserstate
  SpendiQ/SpendiQ.xcodeproj/xcuserdata/j.morav.xcuserdatad/xcschemes/xcschememanagement.plist
  SpendiQ/SpendiQ/.DS_Store
  SpendiQ/SpendiQ/Assets.xcassets/.DS_Store
  SpendiQ/SpendiQ/Assets.xcassets/images/Contents.json
  SpendiQ/SpendiQ/Assets.xcassets/images/hornitos.imageset/Contents.json
  SpendiQ/SpendiQ/Assets.xcassets/images/hornitos.imageset/hornitos.png
  SpendiQ/SpendiQ/Assets.xcassets/images/hornitos.png
  SpendiQ/SpendiQ/Assets.xcassets/images/mcdonalds.imageset/Contents.json
  SpendiQ/SpendiQ/Assets.xcassets/images/mcdonalds.imageset/mcdonalds.png
  SpendiQ/SpendiQ/Assets.xcassets/images/mcdonalds.png
  SpendiQ/SpendiQ/Assets.xcassets/images/puma.imageset/Contents.json
  SpendiQ/SpendiQ/Assets.xcassets/images/puma.imageset/puma.png
  SpendiQ/SpendiQ/Assets.xcassets/images/puma.png
  SpendiQ/SpendiQ/Model/OfferModel.swift
  SpendiQ/SpendiQ/View/OfferBubbleView.swift
  SpendiQ/SpendiQ/View/OfferCardView.swift
  SpendiQ/SpendiQ/View/OfferDetailView.swift
  SpendiQ/SpendiQ/View/PromosPage.swift
  SpendiQ/SpendiQ/ViewModel/OfferViewModel.swift
Labels: bugfix

#14 Feature/HeaderAndIcons
  SpendiQ/SpendiQ.xcodeproj/project.pbxproj
  SpendiQ/SpendiQ.xcodeproj/project.xcworkspace/xcuserdata/j.morav.xcuserdatad/UserInterfaceState.xcuserstate
  SpendiQ/SpendiQ/Assets.xcassets/AppIcon.appiconset/Contents.json
  SpendiQ/SpendiQ/Assets.xcassets/AppIcon.appiconset/dark.png
  SpendiQ/SpendiQ/Assets.xcassets/AppIcon.appiconset/light 1.png
  SpendiQ/SpendiQ/Assets.xcassets/AppIcon.appiconset/light.png
  SpendiQ/SpendiQ/Assets.xcassets/LaunchImage.launchimage/Contents.json
  SpendiQ/SpendiQ/Assets.xcassets/LaunchImage.launchimage/SpendiQ Designs 1.png
  SpendiQ/SpendiQ/Assets.xcassets/LaunchImage.launchimage/SpendiQ Designs 10.png
  SpendiQ/SpendiQ/Assets.xcassets/LaunchImage.launchimage/SpendiQ Designs 11.png
  SpendiQ/SpendiQ/Assets.xcassets/LaunchImage.launchimage/SpendiQ Designs 12.png
  SpendiQ/SpendiQ/Assets.xcassets/LaunchImage.launchimage/SpendiQ Designs 13.png
  SpendiQ/SpendiQ/Assets.xcassets/LaunchImage.launchimage/SpendiQ Designs 14.png
  SpendiQ/SpendiQ/Assets.xcassets/LaunchImage.launchimage/SpendiQ Designs 15.png
  SpendiQ/SpendiQ/Assets.xcassets/LaunchImage.launchimage/SpendiQ Designs 16.png
  SpendiQ/SpendiQ/Assets.xcassets/LaunchImage.launchimage/SpendiQ Designs 17.png
  SpendiQ/SpendiQ/Assets.xcassets/LaunchImage.launchimage/SpendiQ Designs 18.png
  SpendiQ/SpendiQ/Assets.xcassets/LaunchImage.launchimage/SpendiQ Designs 19.png
  SpendiQ/SpendiQ/Assets.xcassets/LaunchImage.launchimage/SpendiQ Designs 2.png
  SpendiQ/SpendiQ/Assets.xcassets/LaunchImage.launchimage/SpendiQ Designs 20.png
  SpendiQ/SpendiQ/Assets.xcassets/LaunchImage.launchimage/SpendiQ Designs 21.png
  SpendiQ/SpendiQ/Assets.xcassets/LaunchImage.launchimage/SpendiQ Designs 22.png
  SpendiQ/SpendiQ/Assets.xcassets/LaunchImage.launchimage/SpendiQ Designs 23.png
  SpendiQ/SpendiQ/Assets.xcassets/LaunchImage.launchimage/SpendiQ Designs 24.png
  SpendiQ/SpendiQ/Assets.xcassets/LaunchImage.launchimage/SpendiQ Designs 25.png
  SpendiQ/SpendiQ/Assets.xcassets/LaunchImage.launchimage/SpendiQ Designs 26.png
  SpendiQ/SpendiQ/Assets.xcassets/LaunchImage.launchimage/SpendiQ Designs 27.png
  SpendiQ/SpendiQ/Assets.xcassets/LaunchImage.launchimage/SpendiQ Designs 28.png
  SpendiQ/SpendiQ/Assets.xcassets/LaunchImage.launchimage/SpendiQ Designs 29.png
  SpendiQ/SpendiQ/Assets.xcassets/LaunchImage.launchimage/SpendiQ Designs 3.png
  SpendiQ/SpendiQ/Assets.xcassets/LaunchImage.launchimage/SpendiQ Designs 30.png
  SpendiQ/SpendiQ/Assets.xcassets/LaunchImage.launchimage/SpendiQ Designs 31.png
  SpendiQ/SpendiQ/Assets.xcassets/LaunchImage.launchimage/SpendiQ Designs 4.png
  SpendiQ/SpendiQ/Assets.xcassets/LaunchImage.launchimage/SpendiQ Designs 5.png
  SpendiQ/SpendiQ/Assets.xcassets/LaunchImage.launchimage/SpendiQ Designs 6.png
  SpendiQ/SpendiQ/Assets.xcassets/LaunchImage.launchimage/SpendiQ Designs 7.png
  SpendiQ/SpendiQ/Assets.xcassets/LaunchImage.launchimage/SpendiQ Designs 8.png
  SpendiQ/SpendiQ/Assets.xcassets/LaunchImage.launchimage/SpendiQ Designs 9.png
  SpendiQ/SpendiQ/Assets.xcassets/LaunchImage.launchimage/SpendiQ Designs.png
  SpendiQ/SpendiQ/Model/UserModel.swift
  SpendiQ/SpendiQ/View/Components/Header.swift
  SpendiQ/SpendiQ/View/ContentView.swift
  SpendiQ/SpendiQ/View/OfferBubbleView.swift
  SpendiQ/SpendiQ/ViewModel/UserViewModel.swift
  SpendiQ/SpendiQ/light.png
Labels: features

#15 Auth Integration
  SpendiQ/SpendiQ/Model/UserModel.swift
  SpendiQ/SpendiQ/Services/AuthenticationService.swift
  SpendiQ/SpendiQ/SpendiQApp.swift
  SpendiQ/SpendiQ/View/AppState.swift
  SpendiQ/SpendiQ/View/AuthenticationView.swift
  SpendiQ/SpendiQ/View/ContentView.swift
  SpendiQ/SpendiQ/View/HomePage.swift
  SpendiQ/SpendiQ/View/LoginView.swift
  SpendiQ/SpendiQ/View/RootView.swift
  SpendiQ/SpendiQ/View/SignUpView.swift
  SpendiQ/SpendiQ/ViewModel/AuthenticationViewModel.swift
  SpendiQ/SpendiQ/ViewModel/UserViewModel.swift
Labels: features

#16 Firestore Feature Implemented
  SpendiQ/SpendiQ/Model/UserModel.swift
  SpendiQ/SpendiQ/Services/AuthenticationService.swift
  SpendiQ/SpendiQ/View/Components/Header.swift
  SpendiQ/SpendiQ/View/SignUpView.swift
  SpendiQ/SpendiQ/ViewModel/AuthenticationViewModel.swift
  SpendiQ/SpendiQ/ViewModel/UserViewModel.swift
Labels: features

#17 Functional Profile View
  SpendiQ/SpendiQ/View/EditProfileView.swift
  SpendiQ/SpendiQ/View/ProfilePage.swift
Labels: features

#18 Feature/smart feature jd
  .DS_Store
  SpendiQ/.DS_Store
  SpendiQ/SpendiQ.xcodeproj/project.pbxproj
  SpendiQ/SpendiQ.xcodeproj/project.xcworkspace/xcuserdata/jdsm.xcuserdatad/UserInterfaceState.xcuserstate
  SpendiQ/SpendiQ/.DS_Store
  SpendiQ/SpendiQ/GoogleService-Info.plist
  SpendiQ/SpendiQ/Model/Movement.swift
  SpendiQ/SpendiQ/NotificationManager.swift
  SpendiQ/SpendiQ/Services/LocationManager.swift
  SpendiQ/SpendiQ/View/Components/MovementForm.swift
  SpendiQ/SpendiQ/View/Components/MovementResume.swift
  SpendiQ/SpendiQ/View/Components/TabBar.swift
  SpendiQ/SpendiQ/View/ContentView.swift
  SpendiQ/SpendiQ/View/HomePage.swift
  SpendiQ/SpendiQ/ViewModel/BankAccountViewModel.swift
  SpendiQ/SpendiQ/ViewModel/TransactionViewModel.swift
Labels: features
